### PR TITLE
ajthinking#15 Fixed port link not center.

### PR DESCRIPTION
**Pull request by fadliabdulrahman**
Screenshot 2021-05-02 at 3 10 42 AM

### CODE REVIEW

**Comment by ajthinking** [comment]
Hey fadliabdulrahman, thanks for the PR 👍 
Did you come via bountysource.com?

* Please merge in latest master
* Drag/release/hover highlight on port bbox works perfect, very nice!
* Pic looks good, but when trying it out locally I get:

image

**Comment by fadliabdulrahman** [comment]
> Hey fadliabdulrahman, thanks for the PR 👍
> Did you come via bountysource.com?
> 
> * Please merge in latest master
> * Drag/release/hover highlight on port bbox works perfect, very nice!
> * Pic looks good, but when trying it out locally I get:
> 
> image
> 
> Google Chrome | 90.0.4430.93

Hello @ajthinking, Yes I'm from the bountysource.com.
Perhaps the unicode fonts that I use only available in Mac. I will check another font to fix this. I will update the PR later..

**Comment by ajthinking** [comment]
Thanks! Will award there then.
Strange, Im also on Mac. Perhaps something like this is safer:
```html
<svg height="500" width="500">
    <polygon points="0,0 100,50 0,100"/>
</svg>
```

**Comment by ajthinking** [comment]
Fixed it in master. I can release bounty to you if you ping me on bountyhunt

**Pull request closed without merging**
